# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentenv < Formula
  desc "AI agent environment management CLI"
  homepage "https://github.com/7emotions/agentenv"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/7emotions/agentenv/releases/download/v0.2.1/agentenv_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "2731058c98520375afdac63a4771c21ac9fcf54633991fcfc6fd95a4cc64805d"

      define_method(:install) do
        bin.install "agentenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/7emotions/agentenv/releases/download/v0.2.1/agentenv_0.2.1_Darwin_aarch64.tar.gz"
      sha256 "c3c39445479fcd3b0e3fb6d24714a9dbe3550e770fe7400f34d58f65eb87f548"

      define_method(:install) do
        bin.install "agentenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/7emotions/agentenv/releases/download/v0.2.1/agentenv_0.2.1_Linux_x86_64.tar.gz"
      sha256 "e00fb1c88290a7323519345f6b345225aaef70f1972c26b3c76fddbacbae0d95"
      define_method(:install) do
        bin.install "agentenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/7emotions/agentenv/releases/download/v0.2.1/agentenv_0.2.1_Linux_aarch64.tar.gz"
      sha256 "0b4b08669bb23ce5c9e8e8c333fc0ca11e1bf713f4cc517cb74f0b4d82bc14fd"
      define_method(:install) do
        bin.install "agentenv"
      end
    end
  end

  test do
    system "#{bin}/agentenv version"
  end
end
