# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentenv < Formula
  desc "AI agent environment management CLI"
  homepage "https://github.com/7emotions/agentenv"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "edda93b85bc46ded745c9515b0bddc80f0f73f51268080b24803ae931ac38422"

      define_method(:install) do
        bin.install "agentenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Darwin_aarch64.tar.gz"
      sha256 "ef4629d9d85ee3c57100d2eb1fdb9c237a42cb43d6875a0183370a72b479e83c"

      define_method(:install) do
        bin.install "agentenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Linux_x86_64.tar.gz"
      sha256 "f5154650f284bff4fb50aa316f0481e68a24a49fe53eafd5c19468c0d249fbd6"
      define_method(:install) do
        bin.install "agentenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Linux_aarch64.tar.gz"
      sha256 "991ddeae4e7eb973ff2fe8304eb8074d42fbe3f3e94477be66a6e877e1a52c8e"
      define_method(:install) do
        bin.install "agentenv"
      end
    end
  end

  test do
    system "#{bin}/agentenv version"
  end
end
