# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentenv < Formula
  desc "AI agent environment management CLI"
  homepage "https://github.com/7emotions/agentenv"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "67189e16a1e2762a0a36e14a65484a673d4dd163b4b3412bcd099f71bee643cb"

      define_method(:install) do
        bin.install "agentenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Darwin_aarch64.tar.gz"
      sha256 "7ab106f445269da73860c3bed4521709c1c0b6f30771168e537eb34167669a64"

      define_method(:install) do
        bin.install "agentenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Linux_x86_64.tar.gz"
      sha256 "68362be8c72e5dba246d069080334bb5715d8045e8a5ceaadaabd92dbc7085f9"
      define_method(:install) do
        bin.install "agentenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/7emotions/agentenv/releases/download/v0.4.0/agentenv_0.4.0_Linux_aarch64.tar.gz"
      sha256 "af18ec2bcbe92d43947b81f78949d6c48291e204228130eec3c77ccf84b3782d"
      define_method(:install) do
        bin.install "agentenv"
      end
    end
  end

  test do
    system "#{bin}/agentenv version"
  end
end
